### PR TITLE
An example for the wiki

### PR DESCRIPTION
**Pull request by nbauma109**
Hello

I think the right place for an example like this is the wiki

Thanks
Nicolas

### CODE REVIEW

**Comment by eugener** [comment]
`JXTable` is an enhanced `JTable` as far as I remember, so nothing new here. Am I missing something?
Wiki actually has the [example of `JXTable` filter Implementation](https://github.com/eugener/oxbow/wiki/JXTable-Filter-Implementation)

**Comment by nbauma109** [comment]
It's an example of integration with maven. I picked up the latest dependency that I found, which is swingbits 1.2.2, but I couldn't make it work until I added checkListRenderer(new CheckListRenderer()). Therefore I think that might be helpful to other users.

**Comment by eugener** [comment]
I see. Would it be ok if, instead of excepting this pull request, I will copy it's content into a new Wiki page?

**Comment by nbauma109** [comment]
sure! thanks!

**Comment by eugener** [comment]
Done... Check it out at https://github.com/eugener/oxbow/wiki/Example-of-Maven-configuration
Thank you!

**Pull request closed without merging**
